name: Test action
on:
  push:
jobs:
  should-update-deployment-status:
    name: Should update deployment status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: dimw/mockbin-action@v1
        with:
          commands: curl

      - name: Act
        uses: './'
        with:
          token: foo
          deployment-id: 123
          status: bar

      - uses: dimw/mockbin-action@v1
        with:
          commands: curl
          assert-args: '["--header", "Authorization: token foo", "--header", "Accept: application\\/vnd\\.github\\.v3\\+json", "--request", "POST", "https://api.github.com/repos/sendinblue/deployment-status-action/deployments/123/statuses", "--data", "{\"state\":\"bar\"}"]'
